# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 527086aafad2c80e82f73e6fbe66b46ea982629f935dacc458de5a4644820a75d821ec8140d6bfd1e3a613d82f16445c695dba50634f0dd942650db579ba99d8

test:
  secret_key_base: 96d01c6247f4dd2acab6919a9b22bec6902edb5f0dbaaddebee9abee70b2cf26065135a1fc220317f03365d15e092775c739687faf5ee98e2c0c44ad031fb564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
